### ISSUE TITLE
Some files are not checked in

### ISSUE THREAD

**Issue by fly-man-** [trevoranderson/twitchbet#1]
It looks like you didn't submit the following files:

controllers/channel.js
watcherbots/accounts.js
watcherbots/watchers.js

Please make sure you commit those so the bot won't crash every 10 seconds

**Comment by trevoranderson** [comment]
I can't find any references to those files in the committed code. Can you verify this is the right repository, and if so, could you paste the error message?

**Comment by fly-man-** [comment]
Of course, those files aren't checked in. It might be that you forgot to check those in as they are referenced in your build file (betbot.njsproj):
-    Compile Include="AmiiboBetter\AmiiboBetter\watcherbots\watchers.js" /
-    Compile Include="AmiiboBetter\AmiiboBetter\controllers\channel.js" /
-    Content Include="AmiiboBetter\AmiiboBetter\watcherbots\accounts.js" /

**Comment by trevoranderson** [comment]
oh, just remove that file, and run node app.js. I'm not sure why I included it. It should work now

**Comment by fly-man-** [comment]
It still won't work since you didn't check in those files which the app.js also references.

My feeling is that those files are crucially the files that the bot needs to recognize on which channel it has to do things.

https://github.com/trevoranderson/twitchbet/blob/master/AmiiboBetter/AmiiboBetter/app.js#L26

https://github.com/trevoranderson/twitchbet/blob/master/AmiiboBetter/AmiiboBetter/app.js#L84
https://github.com/trevoranderson/twitchbet/blob/master/AmiiboBetter/AmiiboBetter/app.js#L87

Could you please check those files in ?

**Comment by trevoranderson** [comment]
Alright, I figured out that I had local commits on a different machine than I normally use that I hadn't pushed. Try it again now.

**Comment by fly-man-** [comment]
Thank you, that did indeed fix the problem :)
